version: '3.1'
services:

  ssdd-frontend:
    build: frontend/.
    ports:
      - 5000:5000
    env_file: mongo.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=true

  db-mongo:
    build: db-mongo/.
    restart: always
    ports:
      - 27017:27017 
    env_file: mongo.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=ssdd

  backend-rest:
    build: backend-rest/es.um.sisdist.backend.Service/.
    ports:
      - 8080:8080
    env_file: mongo.env

  backend-grpc:
    build: backend-grpc/es.um.sisdist.backend.grpc.GrpcServiceImpl/.
    ports:
      - 50051:50051
    env_file: mongo.env

